# Generated by Django 5.2.8 on 2025-11-12 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('urlIcono', models.CharField(blank=True, max_length=255, null=True)),
                ('urlImagen', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('nombreDisplay', models.CharField(blank=True, max_length=200, null=True)),
                ('varFoto', models.CharField(blank=True, max_length=255, null=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=10)),
                ('direccionCompleta', models.CharField(blank=True, max_length=255, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('canton', models.CharField(blank=True, max_length=100, null=True)),
                ('parroquia', models.CharField(blank=True, max_length=100, null=True)),
                ('horarios', models.CharField(blank=True, max_length=255, null=True)),
                ('contacto', models.CharField(blank=True, max_length=200, null=True)),
                ('urlImagenPrincipal', models.CharField(blank=True, max_length=255, null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('urlImagen', models.CharField(blank=True, max_length=255, null=True)),
                ('fechaEvento', models.DateTimeField()),
                ('categoriaEvento', models.CharField(blank=True, max_length=100, null=True)),
                ('direccionAlternativa', models.CharField(blank=True, max_length=255, null=True)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.lugar')),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('visibilidadRuta', models.CharField(max_length=50)),
                ('urlImagenPortada', models.CharField(blank=True, max_length=255, null=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('duracionEstimadaSeg', models.IntegerField()),
                ('distanciaEstimadaKm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('calificacion', models.IntegerField()),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.lugar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Ruta_Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaGuardado', models.DateTimeField(auto_now_add=True)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.lugar')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.ruta')),
            ],
            options={
                'unique_together': {('ruta', 'lugar')},
            },
        ),
        migrations.CreateModel(
            name='Ruta_Guardada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('fechaGuardado', models.DateTimeField(auto_now_add=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.ruta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'ruta')},
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaGuardado', models.DateTimeField(auto_now_add=True)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.lugar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'lugar')},
            },
        ),
    ]
