# Generated by Django 5.2.8 on 2025-12-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ruta_lugar',
            options={'ordering': ['orden']},
        ),
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='lugar',
            name='categoria',
        ),
        migrations.AddField(
            model_name='favorito',
            name='tipo',
            field=models.CharField(choices=[('FAV', 'Favorito'), ('PEND', 'Pendiente'), ('VISIT', 'Visitado')], default='FAV', max_length=10),
        ),
        migrations.AddField(
            model_name='lugar',
            name='categorias',
            field=models.ManyToManyField(related_name='lugares', to='app1.categoria'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='categorias',
            field=models.ManyToManyField(related_name='rutas', to='app1.categoria'),
        ),
        migrations.AddField(
            model_name='ruta_lugar',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together={('usuario', 'lugar', 'tipo')},
        ),
    ]
