# Generated by Django 5.2.8 on 2025-12-11 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_ruta_lugar_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='resena',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='app1.ruta'),
        ),
        migrations.AddField(
            model_name='ruta_lugar',
            name='tiempo_sugerido_minutos',
            field=models.PositiveIntegerField(default=0, help_text='Tiempo sugerido en minutos para esta parada'),
        ),
        migrations.AlterField(
            model_name='resena',
            name='lugar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='app1.lugar'),
        ),
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('canton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parroquias', to='app1.canton')),
            ],
            options={
                'unique_together': {('nombre', 'canton')},
            },
        ),
        migrations.AddField(
            model_name='lugar',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lugares', to='app1.parroquia'),
        ),
        migrations.AddField(
            model_name='canton',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cantones', to='app1.provincia'),
        ),
        migrations.AlterUniqueTogether(
            name='canton',
            unique_together={('nombre', 'provincia')},
        ),
    ]
