# Generated by Django 5.2.8 on 2025-12-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_canton_provincia_resena_ruta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta_lugar',
            name='comentario',
            field=models.TextField(blank=True, help_text='Comentario o nota sobre esta parada en la ruta', null=True),
        ),
    ]
