# Generated by Django 5.2.8 on 2025-12-18 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_ruta_lugar_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('TURISTA', 'Turista'), ('ADMIN', 'Admin App')], default='TURISTA', max_length=20),
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EXPERIENCIA', 'Experiencia'), ('PROMOCION', 'Promoción'), ('EVENTO', 'Evento')], default='EXPERIENCIA', max_length=20)),
                ('archivo_media', models.ImageField(blank=True, null=True, upload_to='publicaciones/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('es_visible', models.BooleanField(default=True)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='app1.lugar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='app1.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='AdministradorLugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administradores', to='app1.lugar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lugares_administrados', to='app1.usuario')),
            ],
            options={
                'verbose_name': 'Administrador de Lugar',
                'verbose_name_plural': 'Administradores de Lugares',
                'unique_together': {('usuario', 'lugar')},
            },
        ),
    ]
